const mongoose = require('mongoose');

/**
 * RSVP Schema — represents a single guest attendance confirmation.
 * @property {string}  name      - Guest full name (required, trimmed)
 * @property {boolean} accepted  - Attendance confirmed (default: true)
 * @property {number}  maxGuests - Total party size including respondent (min: 1)
 * @property {Date}    createdAt - Auto-generated by Mongoose timestamps
 * @property {Date}    updatedAt - Auto-generated by Mongoose timestamps
 */
const rsvpSchema = new mongoose.Schema(
  {
    name: {
      type:      String,
      required:  [true, 'Name is required'],
      trim:      true,
      minlength: [1, 'Name cannot be empty'],
    },
    accepted: {
      type:    Boolean,
      default: true,
    },
    maxGuests: {
      type:     Number,
      required: [true, 'Party size is required'],
      min:      [1, 'Party size must be at least 1'],
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Rsvp', rsvpSchema);
